### ISSUE TITLE
"View In you space" fails on IOS with v4.1.0 -> exporter.parseAsync is not a function

### ISSUE THREAD

**Issue by CrystalDesignMT** [google/model-viewer#5113]
I get this error:

ar.js?50eb:357 Unhandled Promise Rejection: TypeError: exporter.parseAsync is not a function. (In 'exporter.parseAsync(model, {
                maxTextureSize: isNaN(this.arUsdzMaxTextureSize) ?
                    Infinity :
                  ...
(anonymous) @ ar.js?50eb:357

When trying to open the following glb File on IOS 26.1/Safari using model-viewer v4.1.0.
It works on v3.5.0 or when using android

To reproduce:
1. open https://modelviewer.dev/editor/
2. download and drag this file https://gwcstoragedservices.blob.core.windows.net/delete-simple/ZhfeF02k8JSm2zM3rxPSa%20(1).glb into the editor
3. Deploy Mobile and press View in you space on the device

**Comment by smirnov-artur** [comment]
This isn't an iOS 26.1 regression and it isn't in model-viewer — `parseAsync` belongs to three.js, and the copy of three your build resolves is older than r164.

`packages/model-viewer/src/features/ar.ts` imports the exporter straight from three (line 17), and in 4.1.0 calls it like this (ar.ts:454):

```ts
import {USDZExporter} from 'three/examples/jsm/exporters/USDZExporter.js';
...
const arraybuffer = await exporter.parseAsync(model, {maxTextureSize: ...});
```

`parseAsync` first appears in three **r164**. Through r163 the class had only `async parse( scene, options = {} )`. So on any three at r163 or below that call is literally `undefined` — your exact message.

model-viewer 4.1.0 declares `"peerDependencies": {"three": "^0.172.0"}`, so this only shows up when the peer isn't really satisfied: installed with `--legacy-peer-deps`, `three` pinned older elsewhere in the tree, or a second nested copy winning resolution. The `ar.js?50eb` in your stack is a webpack module id, so you're building from `lib/` and `three` comes from your own `node_modules`, not from a self-contained model-viewer bundle. `npm ls three` should show which one it is.

Android is unaffected because the USDZ is only built on the Quick Look path — `[$openIOSARQuickLook]()` → `prepareUSDZ()`. Scene Viewer receives the GLB as-is, so that line never executes there. Same reason 3.5.0 "works": it called the old API (v3.5.0 ar.ts:449), `const arraybuffer = await exporter.parse(model);`.

Two things that look like fixes and aren't:

**Staying on 3.5.0.** From r164 onward `parse` is the callback form, and it is not async:

```js
parse( scene, onDone, onError, options ) {
    this.parseAsync( scene, options ).then( onDone ).catch( onError );
}
```

It returns `undefined`. So the moment your three moves past r163, `await exporter.parse(model)` yields `undefined`, that goes into `new Blob([undefined])`, and Quick Look opens on something that isn't a USDZ. This time with no console error at all — considerably worse to chase than the failure you have now.

**`ar-modes="webxr scene-viewer"`** to route around the exporter. Safari supports neither, so you don't get a fallback, you get no AR button.

What actually fixes it: raise three to what your model-viewer expects (`^0.172` for 4.1.0, `^0.183` on main) and dedupe so exactly one copy is resolved.

If you would rather Safari not do the conversion on the device at all, `ios-src` short-circuits it — `const generateUsdz = !this.iosSrc;` — a pre-baked `.usdz` skips `prepareUSDZ()` entirely. For a fixed catalogue that is also faster on first tap, and it lets you choose texture resolution yourself instead of leaving it to `arUsdzMaxTextureSize`, whose default `auto` resolves to `Infinity`, i.e. no downscale at all.

**Comment by CrystalDesignMT** [comment]
@smirnov-artur  nope what you are staying is almost certainly wrong as:
1. you can reproduce it on their official website as i stated and i doubt they use the wrong three.js version there 
2. we never installed it with --legacy-peer-deps

**Comment by CrystalDesignMT** [comment]
found the problem it's due to the model having 3 uv layers even tough only one is used, giving some feedback in the model-viewer / the validation report would still be something to do imho

**Comment by goncharovart** [comment]
Good find — and worth separating, because there are two different failures in this thread and they have different causes.

**`exporter.parseAsync is not a function`** is purely a version mismatch. I just checked the tags directly:

| three.js | USDZExporter |
|---|---|
| r163 | `async parse( scene, options = {} )` — no `parseAsync` at all |
| r164 | `parseAsync` added; `parse()` kept as a thin wrapper calling it |

So whatever resolves as `three` in a build that throws that message is r163 or older, regardless of what the top-level package.json asks for. On the official site it would mean their deployed bundle, not your install.

**Your UV finding is a separate thing, and the exporter is not dropping those layers — it is writing all of them.** Same file, the mesh writer has always looped over four sets:

```js
for ( let i = 0; i < 4; i ++ ) {
  const id = i > 0 ? i : '';
  const attribute = attributes[ 'uv' + id ];
  if ( attribute !== undefined ) {
    node.addProperty( `texCoord2f[] primvars:st${id} = [...]`, [ 'interpolation = "vertex"' ] );
  }
}
```

That loop is present in r163 and unchanged through r180. Meanwhile the material side picks exactly one channel:

```js
const uv = texture.channel > 0 ? 'st' + texture.channel : 'st';
```

So a mesh with three UV sets where only one is used still ships `primvars:st`, `st1` and `st2` into the .usda — every vertex written three times over — while the shader reads one of them. That is why deleting the unused layers fixed it for you: fewer primvars, smaller and simpler USD, not a different code path. Which of the two it actually is on the QuickLook side — a size limit or a validation refusal — I have not measured, so I am not going to claim it.

Which makes your suggestion the right one: this is exactly the class of thing a validation report should surface, because the model looks fine everywhere else and only USDZ cares. A cheap version would be a warning when a mesh carries UV sets that no material channel references — that is checkable from the parsed glTF alone, before any export runs.

If a reproducible case would help, I am happy to put together a minimal glb with three UV sets and one referenced, plus the resulting .usda, so the difference is visible rather than argued about.

**Comment by smirnov-artur** [comment]
Good find — and worth separating, because there are two different failures in this thread and they have different causes.

**`exporter.parseAsync is not a function`** is purely a version mismatch. I just checked the tags directly:

| three.js | USDZExporter |
|---|---|
| r163 | `async parse( scene, options = {} )` — no `parseAsync` at all |
| r164 | `parseAsync` added; `parse()` kept as a thin wrapper calling it |

So whatever resolves as `three` in a build that throws that message is r163 or older, regardless of what the top-level package.json asks for. On the official site it would mean their deployed bundle, not your install.

**Your UV finding is a separate thing, and the exporter is not dropping those layers — it is writing all of them.** Same file, the mesh writer has always looped over four sets:

```js
for ( let i = 0; i < 4; i ++ ) {
  const id = i > 0 ? i : '';
  const attribute = attributes[ 'uv' + id ];
  if ( attribute !== undefined ) {
    node.addProperty( `texCoord2f[] primvars:st${id} = [...]`, [ 'interpolation = "vertex"' ] );
  }
}
```

That loop is present in r163 and unchanged through r180. Meanwhile the material side picks exactly one channel:

```js
const uv = texture.channel > 0 ? 'st' + texture.channel : 'st';
```

So a mesh with three UV sets where only one is used still ships `primvars:st`, `st1` and `st2` into the .usda — every vertex written three times over — while the shader reads one of them. That is why deleting the unused layers fixed it for you: fewer primvars, smaller and simpler USD, not a different code path. Which of the two it actually is on the QuickLook side — a size limit or a validation refusal — I have not measured, so I am not going to claim it.

Which makes your suggestion the right one: this is exactly the class of thing a validation report should surface, because the model looks fine everywhere else and only USDZ cares. A cheap version would be a warning when a mesh carries UV sets that no material channel references — that is checkable from the parsed glTF alone, before any export runs.

If a reproducible case would help, I am happy to put together a minimal glb with three UV sets and one referenced, plus the resulting .usda, so the difference is visible rather than argued about.
